version: '3'
services:
  envoy:
    image: envoyproxy/envoy:v1.25.1
    container_name: envoy
    restart: always
    volumes:
      - /root/envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - /root/envoy/:/root/envoy/
      - /root/logs/envoy/:/root/logs/envoy/
    environment:
    - "ENVOY_UID=0"
    network_mode: host
